export type ReferenceKind="capital"|"city"|"airport"|"port"|"energy"|"crossing"|"corridor";
export type ReferencePin={id:string;name:string;province:string;lat:number;lng:number;kind:ReferenceKind;detail:string};

export const referencePins:ReferencePin[]=[
// Federal, provincial and territorial capitals
{id:"ottawa",name:"Ottawa",province:"ON",lat:45.4215,lng:-75.6972,kind:"capital",detail:"Federal capital / national institutions"},
{id:"victoria",name:"Victoria",province:"BC",lat:48.4284,lng:-123.3656,kind:"capital",detail:"Provincial capital"},
{id:"edmonton",name:"Edmonton",province:"AB",lat:53.5461,lng:-113.4938,kind:"capital",detail:"Provincial capital"},
{id:"regina",name:"Regina",province:"SK",lat:50.4452,lng:-104.6189,kind:"capital",detail:"Provincial capital"},
{id:"winnipeg",name:"Winnipeg",province:"MB",lat:49.8951,lng:-97.1384,kind:"capital",detail:"Provincial capital"},
{id:"toronto",name:"Toronto",province:"ON",lat:43.6532,lng:-79.3832,kind:"capital",detail:"Provincial capital / major economic centre"},
{id:"quebec-city",name:"Québec City",province:"QC",lat:46.8139,lng:-71.2080,kind:"capital",detail:"Provincial capital"},
{id:"fredericton",name:"Fredericton",province:"NB",lat:45.9636,lng:-66.6431,kind:"capital",detail:"Provincial capital"},
{id:"halifax",name:"Halifax",province:"NS",lat:44.6488,lng:-63.5752,kind:"capital",detail:"Provincial capital / Atlantic hub"},
{id:"charlottetown",name:"Charlottetown",province:"PE",lat:46.2382,lng:-63.1311,kind:"capital",detail:"Provincial capital"},
{id:"st-johns",name:"St. John's",province:"NL",lat:47.5615,lng:-52.7126,kind:"capital",detail:"Provincial capital"},
{id:"whitehorse",name:"Whitehorse",province:"YT",lat:60.7212,lng:-135.0568,kind:"capital",detail:"Territorial capital"},
{id:"yellowknife",name:"Yellowknife",province:"NT",lat:62.4540,lng:-114.3718,kind:"capital",detail:"Territorial capital"},
{id:"iqaluit",name:"Iqaluit",province:"NU",lat:63.7467,lng:-68.5170,kind:"capital",detail:"Territorial capital"},
// Population / regional centres
{id:"vancouver",name:"Vancouver",province:"BC",lat:49.2827,lng:-123.1207,kind:"city",detail:"Metro / Pacific gateway"},
{id:"surrey",name:"Surrey",province:"BC",lat:49.1913,lng:-122.8490,kind:"city",detail:"Lower Mainland population centre"},
{id:"kelowna",name:"Kelowna",province:"BC",lat:49.8880,lng:-119.4960,kind:"city",detail:"Interior regional centre"},
{id:"kamloops",name:"Kamloops",province:"BC",lat:50.6745,lng:-120.3273,kind:"city",detail:"Interior transport node"},
{id:"prince-george",name:"Prince George",province:"BC",lat:53.9171,lng:-122.7497,kind:"city",detail:"Northern BC regional centre"},
{id:"nanaimo",name:"Nanaimo",province:"BC",lat:49.1659,lng:-123.9401,kind:"city",detail:"Vancouver Island centre"},
{id:"calgary",name:"Calgary",province:"AB",lat:51.0447,lng:-114.0719,kind:"city",detail:"Major economic and energy centre"},
{id:"red-deer",name:"Red Deer",province:"AB",lat:52.2681,lng:-113.8112,kind:"city",detail:"Central Alberta corridor"},
{id:"fort-mcmurray",name:"Fort McMurray",province:"AB",lat:56.7264,lng:-111.3803,kind:"city",detail:"Oil sands service centre"},
{id:"lethbridge",name:"Lethbridge",province:"AB",lat:49.6956,lng:-112.8451,kind:"city",detail:"Southern Alberta regional centre"},
{id:"medicine-hat",name:"Medicine Hat",province:"AB",lat:50.0405,lng:-110.6765,kind:"city",detail:"Southeast Alberta centre"},
{id:"saskatoon",name:"Saskatoon",province:"SK",lat:52.1332,lng:-106.6700,kind:"city",detail:"Largest Saskatchewan metro"},
{id:"prince-albert",name:"Prince Albert",province:"SK",lat:53.2033,lng:-105.7531,kind:"city",detail:"Northern Saskatchewan gateway"},
{id:"moose-jaw",name:"Moose Jaw",province:"SK",lat:50.3933,lng:-105.5519,kind:"city",detail:"Prairie transport centre"},
{id:"brandon",name:"Brandon",province:"MB",lat:49.8485,lng:-99.9501,kind:"city",detail:"Western Manitoba centre"},
{id:"thompson",name:"Thompson",province:"MB",lat:55.7435,lng:-97.8558,kind:"city",detail:"Northern Manitoba hub"},
{id:"churchill",name:"Churchill",province:"MB",lat:58.7684,lng:-94.1650,kind:"city",detail:"Hudson Bay northern gateway"},
{id:"hamilton",name:"Hamilton",province:"ON",lat:43.2557,lng:-79.8711,kind:"city",detail:"Industrial / logistics centre"},
{id:"mississauga",name:"Mississauga",province:"ON",lat:43.5890,lng:-79.6441,kind:"city",detail:"Greater Toronto logistics centre"},
{id:"london",name:"London",province:"ON",lat:42.9849,lng:-81.2453,kind:"city",detail:"Southwestern Ontario regional centre"},
{id:"kitchener",name:"Kitchener-Waterloo",province:"ON",lat:43.4516,lng:-80.4925,kind:"city",detail:"Technology / manufacturing corridor"},
{id:"windsor",name:"Windsor",province:"ON",lat:42.3149,lng:-83.0364,kind:"city",detail:"US border manufacturing gateway"},
{id:"kingston",name:"Kingston",province:"ON",lat:44.2312,lng:-76.4860,kind:"city",detail:"Eastern Ontario corridor"},
{id:"sudbury",name:"Greater Sudbury",province:"ON",lat:46.4917,lng:-80.9930,kind:"city",detail:"Northern Ontario mining centre"},
{id:"thunder-bay",name:"Thunder Bay",province:"ON",lat:48.3809,lng:-89.2477,kind:"city",detail:"Lake Superior transport hub"},
{id:"montreal",name:"Montréal",province:"QC",lat:45.5017,lng:-73.5673,kind:"city",detail:"Major economic / logistics centre"},
{id:"gatineau",name:"Gatineau",province:"QC",lat:45.4765,lng:-75.7013,kind:"city",detail:"National Capital Region"},
{id:"sherbrooke",name:"Sherbrooke",province:"QC",lat:45.4042,lng:-71.8929,kind:"city",detail:"Eastern Townships centre"},
{id:"trois-rivieres",name:"Trois-Rivières",province:"QC",lat:46.3430,lng:-72.5430,kind:"city",detail:"St. Lawrence industrial corridor"},
{id:"saguenay",name:"Saguenay",province:"QC",lat:48.4281,lng:-71.0680,kind:"city",detail:"Saguenay industrial centre"},
{id:"moncton",name:"Moncton",province:"NB",lat:46.0878,lng:-64.7782,kind:"city",detail:"Atlantic logistics hub"},
{id:"saint-john",name:"Saint John",province:"NB",lat:45.2733,lng:-66.0633,kind:"city",detail:"Port / industrial centre"},
{id:"sydney",name:"Sydney",province:"NS",lat:46.1368,lng:-60.1942,kind:"city",detail:"Cape Breton regional centre"},
{id:"truro",name:"Truro",province:"NS",lat:45.3658,lng:-63.2869,kind:"city",detail:"Nova Scotia transport junction"},
{id:"corner-brook",name:"Corner Brook",province:"NL",lat:48.9481,lng:-57.9503,kind:"city",detail:"Western Newfoundland centre"},
{id:"gander",name:"Gander",province:"NL",lat:48.9560,lng:-54.6089,kind:"city",detail:"Central Newfoundland aviation centre"},
{id:"happy-valley",name:"Happy Valley-Goose Bay",province:"NL",lat:53.3017,lng:-60.3258,kind:"city",detail:"Labrador regional hub"},
{id:"dawson-city",name:"Dawson City",province:"YT",lat:64.0601,lng:-139.4320,kind:"city",detail:"Central Yukon community"},
{id:"inuvik",name:"Inuvik",province:"NT",lat:68.3607,lng:-133.7230,kind:"city",detail:"Western Arctic regional hub"},
{id:"hay-river",name:"Hay River",province:"NT",lat:60.8156,lng:-115.7999,kind:"city",detail:"Great Slave Lake transport centre"},
{id:"rankin-inlet",name:"Rankin Inlet",province:"NU",lat:62.8084,lng:-92.0853,kind:"city",detail:"Kivalliq regional hub"},
{id:"cambridge-bay",name:"Cambridge Bay",province:"NU",lat:69.1169,lng:-105.0597,kind:"city",detail:"Kitikmeot regional hub"},
// Major airports
{id:"yvr",name:"Vancouver International (YVR)",province:"BC",lat:49.1951,lng:-123.1779,kind:"airport",detail:"Major international airport"},
{id:"yyj",name:"Victoria International (YYJ)",province:"BC",lat:48.6469,lng:-123.4258,kind:"airport",detail:"Regional / international airport"},
{id:"yeg",name:"Edmonton International (YEG)",province:"AB",lat:53.3097,lng:-113.5800,kind:"airport",detail:"Major prairie aviation hub"},
{id:"yyc",name:"Calgary International (YYC)",province:"AB",lat:51.1215,lng:-114.0076,kind:"airport",detail:"Major international airport"},
{id:"yxe",name:"Saskatoon International (YXE)",province:"SK",lat:52.1708,lng:-106.6997,kind:"airport",detail:"Saskatchewan aviation hub"},
{id:"yqr",name:"Regina International (YQR)",province:"SK",lat:50.4319,lng:-104.6658,kind:"airport",detail:"Saskatchewan aviation hub"},
{id:"ywg",name:"Winnipeg Richardson (YWG)",province:"MB",lat:49.9100,lng:-97.2399,kind:"airport",detail:"Central Canada aviation / cargo hub"},
{id:"yhz",name:"Halifax Stanfield (YHZ)",province:"NS",lat:44.8808,lng:-63.5086,kind:"airport",detail:"Atlantic international airport"},
{id:"yul",name:"Montréal-Trudeau (YUL)",province:"QC",lat:45.4706,lng:-73.7408,kind:"airport",detail:"Major international airport"},
{id:"yqb",name:"Québec City Jean Lesage (YQB)",province:"QC",lat:46.7911,lng:-71.3933,kind:"airport",detail:"Regional / international airport"},
{id:"yyz",name:"Toronto Pearson (YYZ)",province:"ON",lat:43.6777,lng:-79.6248,kind:"airport",detail:"Canada's largest aviation hub"},
{id:"yow",name:"Ottawa International (YOW)",province:"ON",lat:45.3225,lng:-75.6692,kind:"airport",detail:"National Capital Region airport"},
{id:"yqt",name:"Thunder Bay International (YQT)",province:"ON",lat:48.3719,lng:-89.3239,kind:"airport",detail:"Northern Ontario aviation hub"},
{id:"yyt",name:"St. John's International (YYT)",province:"NL",lat:47.6186,lng:-52.7519,kind:"airport",detail:"Newfoundland aviation hub"},
{id:"yxy",name:"Whitehorse International (YXY)",province:"YT",lat:60.7096,lng:-135.0670,kind:"airport",detail:"Yukon aviation hub"},
{id:"yzf",name:"Yellowknife Airport (YZF)",province:"NT",lat:62.4628,lng:-114.4403,kind:"airport",detail:"Northwest Territories aviation hub"},
{id:"yfb",name:"Iqaluit Airport (YFB)",province:"NU",lat:63.7564,lng:-68.5558,kind:"airport",detail:"Nunavut aviation hub"},
// Major ports / marine gateways
{id:"port-vancouver",name:"Port of Vancouver",province:"BC",lat:49.2965,lng:-123.1120,kind:"port",detail:"Pacific container / bulk gateway"},
{id:"port-prince-rupert",name:"Port of Prince Rupert",province:"BC",lat:54.3150,lng:-130.3200,kind:"port",detail:"Pacific trade gateway"},
{id:"port-montreal",name:"Port of Montréal",province:"QC",lat:45.5570,lng:-73.5200,kind:"port",detail:"St. Lawrence container gateway"},
{id:"port-quebec",name:"Port of Québec",province:"QC",lat:46.8240,lng:-71.2050,kind:"port",detail:"St. Lawrence bulk / cruise port"},
{id:"port-halifax",name:"Port of Halifax",province:"NS",lat:44.6360,lng:-63.5680,kind:"port",detail:"Atlantic container gateway"},
{id:"port-saint-john",name:"Port Saint John",province:"NB",lat:45.2620,lng:-66.0570,kind:"port",detail:"Atlantic industrial / cargo port"},
{id:"port-thunder-bay",name:"Port of Thunder Bay",province:"ON",lat:48.3930,lng:-89.2150,kind:"port",detail:"Great Lakes grain / bulk gateway"},
{id:"port-hamilton",name:"Port of Hamilton",province:"ON",lat:43.2870,lng:-79.7900,kind:"port",detail:"Great Lakes industrial port"},
{id:"port-churchill",name:"Port of Churchill",province:"MB",lat:58.7670,lng:-94.2040,kind:"port",detail:"Hudson Bay northern port"},
{id:"port-stjohns",name:"Port of St. John's",province:"NL",lat:47.5650,lng:-52.7040,kind:"port",detail:"Atlantic / offshore service port"},
// Energy system reference sites (public, approximate)
{id:"site-c",name:"Site C",province:"BC",lat:56.205,lng:-120.900,kind:"energy",detail:"Hydroelectric generation site"},
{id:"mica",name:"Mica Generating Station",province:"BC",lat:52.074,lng:-118.567,kind:"energy",detail:"Major hydroelectric generation"},
{id:"wac-bennett",name:"W.A.C. Bennett Dam",province:"BC",lat:56.015,lng:-122.205,kind:"energy",detail:"Major hydroelectric generation"},
{id:"shepard",name:"Shepard Energy Centre",province:"AB",lat:50.943,lng:-113.875,kind:"energy",detail:"Natural gas power generation"},
{id:"boundary-dam",name:"Boundary Dam",province:"SK",lat:49.095,lng:-103.031,kind:"energy",detail:"Thermal generation / CCS reference site"},
{id:"keeyask",name:"Keeyask Generating Station",province:"MB",lat:56.348,lng:-95.061,kind:"energy",detail:"Hydroelectric generation"},
{id:"nelson-river",name:"Kettle Generating Station",province:"MB",lat:56.379,lng:-94.629,kind:"energy",detail:"Nelson River hydroelectric generation"},
{id:"bruce",name:"Bruce Nuclear",province:"ON",lat:44.325,lng:-81.600,kind:"energy",detail:"Nuclear generation complex"},
{id:"darlington",name:"Darlington Nuclear",province:"ON",lat:43.872,lng:-78.719,kind:"energy",detail:"Nuclear generation complex"},
{id:"pickering",name:"Pickering Nuclear",province:"ON",lat:43.811,lng:-79.066,kind:"energy",detail:"Nuclear generation complex"},
{id:"beauharnois",name:"Beauharnois Generating Station",province:"QC",lat:45.316,lng:-73.907,kind:"energy",detail:"Hydroelectric generation"},
{id:"robert-bourassa",name:"Robert-Bourassa Generating Station",province:"QC",lat:53.785,lng:-77.558,kind:"energy",detail:"James Bay hydroelectric generation"},
{id:"churchill-falls",name:"Churchill Falls Generating Station",province:"NL",lat:53.532,lng:-64.106,kind:"energy",detail:"Major hydroelectric generation"},
{id:"point-lepreau",name:"Point Lepreau Nuclear",province:"NB",lat:45.069,lng:-66.456,kind:"energy",detail:"Nuclear generation station"},
{id:"tobique",name:"Tobique Narrows",province:"NB",lat:46.778,lng:-67.695,kind:"energy",detail:"Hydroelectric generation"},
{id:"muskrat-falls",name:"Muskrat Falls",province:"NL",lat:53.247,lng:-60.766,kind:"energy",detail:"Lower Churchill hydroelectric generation"},
// High-volume / strategic road-border reference crossings
{id:"peace-arch",name:"Peace Arch / Douglas",province:"BC",lat:49.002,lng:-122.756,kind:"crossing",detail:"Canada–US road border crossing"},
{id:"pacific-highway",name:"Pacific Highway",province:"BC",lat:49.003,lng:-122.735,kind:"crossing",detail:"Commercial Canada–US border crossing"},
{id:"coutts",name:"Coutts / Sweetgrass",province:"AB",lat:49.000,lng:-111.961,kind:"crossing",detail:"Major prairie commercial border crossing"},
{id:"north-portal",name:"North Portal",province:"SK",lat:49.000,lng:-102.550,kind:"crossing",detail:"Prairie road / freight crossing"},
{id:"emerson",name:"Emerson",province:"MB",lat:49.000,lng:-97.237,kind:"crossing",detail:"Major Manitoba road / freight crossing"},
{id:"ambassador",name:"Ambassador Bridge",province:"ON",lat:42.312,lng:-83.074,kind:"crossing",detail:"Major Canada–US trade crossing"},
{id:"blue-water",name:"Blue Water Bridge",province:"ON",lat:42.999,lng:-82.424,kind:"crossing",detail:"Major Ontario–US trade crossing"},
{id:"peace-bridge",name:"Peace Bridge",province:"ON",lat:42.907,lng:-78.905,kind:"crossing",detail:"Niagara Canada–US crossing"},
{id:"queenston",name:"Queenston–Lewiston",province:"ON",lat:43.154,lng:-79.052,kind:"crossing",detail:"Niagara commercial crossing"},
{id:"lacolle",name:"Saint-Bernard-de-Lacolle",province:"QC",lat:45.005,lng:-73.455,kind:"crossing",detail:"Major Québec–US road crossing"},
{id:"stanstead",name:"Stanstead",province:"QC",lat:45.006,lng:-72.099,kind:"crossing",detail:"Québec–Vermont road crossing"},
{id:"woodstock",name:"Woodstock / Houlton",province:"NB",lat:46.138,lng:-67.785,kind:"crossing",detail:"New Brunswick–Maine road crossing"},
// National corridors / chokepoints
{id:"fraser-corridor",name:"Fraser Valley Corridor",province:"BC",lat:49.105,lng:-121.960,kind:"corridor",detail:"Highway / rail / supply-chain corridor"},
{id:"rogers-pass",name:"Rogers Pass",province:"BC",lat:51.301,lng:-117.517,kind:"corridor",detail:"Trans-Canada mountain corridor"},
{id:"yellowhead-edmonton",name:"Yellowhead Corridor — Edmonton",province:"AB",lat:53.579,lng:-113.489,kind:"corridor",detail:"National road / rail corridor"},
{id:"winnipeg-gateway",name:"Winnipeg Continental Gateway",province:"MB",lat:49.900,lng:-97.140,kind:"corridor",detail:"National rail / road interchange"},
{id:"gta-gateway",name:"GTA Trade Gateway",province:"ON",lat:43.700,lng:-79.600,kind:"corridor",detail:"High-density national freight corridor"},
{id:"montreal-gateway",name:"Montréal Gateway",province:"QC",lat:45.520,lng:-73.600,kind:"corridor",detail:"St. Lawrence / rail / road gateway"},
{id:"canso-strait",name:"Strait of Canso",province:"NS",lat:45.650,lng:-61.400,kind:"corridor",detail:"Atlantic marine / industrial corridor"},
];
