"use client";
import {useEffect,useMemo,useState} from "react";
import {metros,type Metro} from "./city-data";
import {referencePins} from "./canada-reference-pins";

type Severity="critical"|"elevated"|"watch"|"stable";
type LiveEvent={id:string;title:string;summary:string;lat:number;lng:number;severity:Severity;source:string;sourceUrl:string;category:string;occurredAt:string;location?:string};
type Scenario={homes:number;cleanPower:number;transit:number;health:number;adaptation:number;productivity:number};
type CityMetric={id:string;label:string;value:string;raw?:number;detail:string;source:string;sourceUrl:string;observedAt?:string;cadence:string;change?:string;group:"people"|"housing"|"economy"};
type Payload={city:Metro;fetchedAt:string;metrics:CityMetric[];available:number;total:number};
type Tab="overview"|"live"|"people"|"housing"|"economy"|"infra"|"environment"|"projections"|"compare";
type Lens="24H"|"7D"|"30D"|"1Y"|"5Y"|"10Y";
const hav=(a:number,b:number,c:number,d:number)=>{const R=6371,to=(x:number)=>x*Math.PI/180,dl=to(c-a),dn=to(d-b),q=Math.sin(dl/2)**2+Math.cos(to(a))*Math.cos(to(c))*Math.sin(dn/2)**2;return 2*R*Math.asin(Math.sqrt(q))};
const lensMs:Record<Lens,number>={"24H":86400000,"7D":604800000,"30D":2592000000,"1Y":31536000000,"5Y":157680000000,"10Y":315360000000};
const scoreTone=(v:number)=>v>=75?"strong":v>=55?"balanced":v>=35?"watch":"strained";

export default function CityIntelligencePanel({events,scenario,horizon,selectedCity,onCitySelect}:{events:LiveEvent[];scenario:Scenario;horizon:number;selectedCity:string;onCitySelect:(id:string)=>void}){
 const [tab,setTab]=useState<Tab>("overview"),[lens,setLens]=useState<Lens>("30D"),[payload,setPayload]=useState<Payload|null>(null),[compareIds,setCompareIds]=useState<string[]>(["toronto","montreal","calgary"]),[compareData,setCompareData]=useState<Record<string,Payload>>({});
 const city=metros.find(m=>m.id===selectedCity)??metros[0];
 useEffect(()=>{let c=false;setPayload(null);fetch(`/api/canada-city-data?city=${encodeURIComponent(city.id)}`).then(r=>r.ok?r.json():Promise.reject()).then(d=>{if(!c)setPayload(d)}).catch(()=>{if(!c)setPayload({city,fetchedAt:new Date().toISOString(),metrics:[],available:0,total:6})});return()=>{c=true}},[city.id]);
 useEffect(()=>{let c=false;Promise.all(compareIds.map(id=>fetch(`/api/canada-city-data?city=${id}`).then(r=>r.ok?r.json():Promise.reject()).catch(()=>null))).then(rows=>{if(c)return;const next:Record<string,Payload>={};rows.forEach((r,i)=>{if(r)next[compareIds[i]]=r});setCompareData(next)});return()=>{c=true}},[compareIds.join("|")]);
 const nearbyAll=useMemo(()=>events.map(e=>({...e,distance:hav(city.lat,city.lng,e.lat,e.lng)})).filter(e=>e.distance<=city.radiusKm*1.8).sort((a,b)=>a.distance-b.distance),[events,city]);
 const now=Date.now(),nearby=nearbyAll.filter(e=>{const t=Date.parse(e.occurredAt);return !Number.isFinite(t)||now-t<=lensMs[lens]});
 const infra=useMemo(()=>referencePins.map(p=>({...p,distance:hav(city.lat,city.lng,p.lat,p.lng)})).filter(p=>p.distance<=city.radiusKm).sort((a,b)=>a.distance-b.distance),[city]);
 const metrics=payload?.metrics??[],by=(id:string)=>metrics.find(m=>m.id===id),pop=by("population")?.raw??city.populationFallback*1e6,starts=by("housing-starts")?.raw??0,unemp=by("unemployment")?.raw??0,permits=by("building-permits")?.raw??0;
 const housingPressure=Math.max(0,Math.min(100,Math.round(68+(pop/1e6)*1.1-(starts/10000)*2.8-scenario.homes*.24))),labourMomentum=Math.max(0,Math.min(100,Math.round(75-unemp*5+scenario.productivity*.16))),infraPressure=Math.max(0,Math.min(100,Math.round(52+(pop/1e6)*3.4-infra.length*.55-scenario.transit*.22-scenario.cleanPower*.12))),envRisk=Math.max(0,Math.min(100,Math.round(nearby.filter(e=>/wildfire|flood|weather|air|storm|fire/i.test(`${e.category} ${e.title}`)).length*9-scenario.adaptation*.25+24)));
 const years=Math.max(1,horizon-2026),growthRate=city.id==="calgary"||city.id==="edmonton"?0.023:city.id==="toronto"||city.id==="vancouver"?0.018:0.012,projectedPop=pop*Math.pow(1+growthRate,years),capacityIndex=Math.max(0,Math.min(100,Math.round(50+((projectedPop-pop)/Math.max(pop,1))*140-scenario.homes*.28-scenario.transit*.15-scenario.health*.12))),requiredHomes=Math.round(((projectedPop-pop)/2.4)*Math.max(.45,1-scenario.homes/180));
 const tabs:Tab[]=["overview","live","people","housing","economy","infra","environment","projections","compare"];
 return <section className="city-intel-panel">
  <div className="sim-section-head city-head"><div><span>05 / LOCAL INTELLIGENCE</span><h3>{city.name} metropolitan situation profile</h3><p>Official CMA releases + nearby Atlas signals + infrastructure context. Local data is only shown where the source actually supports the metro geography.</p></div><div className="city-picker-wrap"><label>METRO<select value={city.id} onChange={e=>onCitySelect(e.target.value)}>{metros.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label><div className="city-source-health"><b>{payload?.available??0}/{payload?.total??6}</b><span>CMA feeds</span></div></div></div>
  <div className="city-tabs">{tabs.map(t=><button key={t} className={tab===t?"active":""} onClick={()=>setTab(t)}>{t}</button>)}</div>
  <div className="city-lens"><span>TIME LENS</span>{(["24H","7D","30D","1Y","5Y","10Y"] as Lens[]).map(x=><button key={x} className={lens===x?"active":""} onClick={()=>setLens(x)}>{x}</button>)}<small>{lens==="24H"||lens==="7D"||lens==="30D"?"filters local live signals":"official releases remain latest available; long lens is contextual"}</small></div>
  {(tab==="overview")&&<div className="city-overview-grid"><div className="city-metric-board"><CityMetricCard metric={by("population")} fallback={`${city.populationFallback.toFixed(2)}M`} label="Population" note="CMA estimate"/><CityMetricCard metric={by("unemployment")} fallback="—" label="Unemployment" note="3-mo avg"/><CityMetricCard metric={by("housing-starts")} fallback="—" label="Housing starts" note="SAAR"/><CityMetricCard metric={by("building-permits")} fallback="—" label="Building permits" note="monthly"/><article><span>LOCAL SIGNALS</span><strong>{nearby.length}</strong><small>{lens} · within ~{Math.round(city.radiusKm*1.8)} km</small></article><article><span>NEARBY INFRA</span><strong>{infra.length}</strong><small>Atlas reference network</small></article></div><div className="city-pulse"><h4>CITY PULSE</h4><Pulse label="Housing pressure" value={housingPressure} inverse/><Pulse label="Labour momentum" value={labourMomentum}/><Pulse label="Infrastructure pressure" value={infraPressure} inverse/><Pulse label="Environmental risk" value={envRisk} inverse/><p>Atlas-derived indicators are transparent directional summaries, not official municipal scores.</p></div><div className="city-context"><span>ECONOMIC PROFILE</span><h4>{city.name}</h4><div>{city.strengths.map(s=><b key={s}>{s}</b>)}</div><p>{city.provinceName} · approximate metro analysis radius {city.radiusKm} km.</p></div></div>}
  {tab==="live"&&<div className="city-list"><SectionIntro title={`${nearby.length} local signals`} copy={`Canada-resolved Atlas events inside the ${city.name} operating area for the selected ${lens} lens.`}/>{nearby.slice(0,24).map(e=><a href={e.sourceUrl} target="_blank" rel="noreferrer" key={e.id}><i className={e.severity}/><div><span>{Math.round(e.distance)} km · {e.category}</span><strong>{e.title}</strong><small>{e.source}</small></div></a>)}{!nearby.length&&<Empty text="No mapped Atlas signals fall inside this metro/time lens."/>}</div>}
  {tab==="people"&&<MetricGroup metrics={metrics.filter(m=>m.group==="people")} intro="Official population estimates for the census metropolitan area."/>}
  {tab==="housing"&&<MetricGroup metrics={metrics.filter(m=>m.group==="housing")} intro="CMHC housing starts and Statistics Canada building-permit releases at CMA geography where available."/>}
  {tab==="economy"&&<MetricGroup metrics={metrics.filter(m=>m.group==="economy")} intro="Monthly CMA labour-market conditions from Statistics Canada's Labour Force Survey."/>}
  {tab==="infra"&&<div className="infra-grid"><SectionIntro title={`${infra.length} nearby reference assets`} copy="Airports, ports, energy, corridors, crossings and other Atlas reference points inside the metro analysis radius."/>{infra.map(p=><article key={p.id}><i className={`infra-${p.kind}`}/><div><span>{p.kind.toUpperCase()} · {Math.round(p.distance)} km</span><strong>{p.name}</strong><small>{p.detail}</small></div></article>)}{!infra.length&&<Empty text="No Atlas reference assets are inside this analysis radius yet."/>}</div>}
  {tab==="environment"&&<div className="environment-board"><SectionIntro title="Local environmental exposure" copy="Nearby hazard/weather/air/water signals from the current Atlas event layer. National ECCC feeds remain available above."/><Pulse label="Environmental risk" value={envRisk} inverse/>{nearby.filter(e=>/wildfire|flood|weather|air|storm|fire|water/i.test(`${e.category} ${e.title}`)).slice(0,12).map(e=><a key={e.id} href={e.sourceUrl} target="_blank" rel="noreferrer"><span>{Math.round(e.distance)} km</span><strong>{e.title}</strong><small>{e.category} · {e.source}</small></a>)}</div>}
  {tab==="projections"&&<div className="city-projection"><SectionIntro title={`${city.name} outlook to ${horizon}`} copy="Atlas scenario projection using the latest returned CMA population as its base when available. Growth assumptions are illustrative and explicitly simulated."/><div className="projection-cards"><article><span>BASE POPULATION</span><strong>{(pop/1e6).toFixed(2)}M</strong><small>{by("population")?.observedAt??"reference"}</small></article><article><span>SIMULATED POPULATION</span><strong>{(projectedPop/1e6).toFixed(2)}M</strong><small>{horizon} · illustrative growth path</small></article><article><span>HOUSING REQUIREMENT</span><strong>{requiredHomes.toLocaleString()}</strong><small>scenario-equivalent incremental homes</small></article><article><span>CAPACITY PRESSURE</span><strong>{capacityIndex}/100</strong><small>after current scenario levers</small></article></div><div className="projection-explain"><b>WHY THIS CHANGES</b><p>Population growth adds demand. Housing delivery, transit, health capacity, power expansion and adaptation reduce modeled pressure. The result is a scenario tool—not a municipal forecast.</p></div></div>}
  {tab==="compare"&&<CompareBoard ids={compareIds} setIds={setCompareIds} data={compareData} events={events}/>} 
 </section>
}
function CityMetricCard({metric,fallback,label,note}:{metric?:CityMetric;fallback:string;label:string;note:string}){return <article><span>{label.toUpperCase()}</span><strong>{metric?.value??fallback}</strong><small>{metric?.change??note}</small></article>}
function Pulse({label,value,inverse=false}:{label:string;value:number;inverse?:boolean}){const safeValue=Math.max(0,Math.min(100,value));const display=inverse?100-safeValue:safeValue;const tone=scoreTone(display);return <div className={`pulse-row ${tone}`}><div><span>{label}</span><b>{safeValue>=70?"HIGH":safeValue>=50?"ELEVATED":safeValue>=30?"MODERATE":"LOW"}</b></div><div className="pulse-track" role="progressbar" aria-label={label} aria-valuemin={0} aria-valuemax={100} aria-valuenow={Math.round(safeValue)}><i style={{width:`${safeValue}%`}}/></div><small>{Math.round(safeValue)}/100 · Atlas derived</small></div>}
function MetricGroup({metrics,intro}:{metrics:CityMetric[];intro:string}){return <div className="city-official"><SectionIntro title="Official metro releases" copy={intro}/><div>{metrics.map(m=><a key={m.id} href={m.sourceUrl} target="_blank" rel="noreferrer"><span>{m.label}</span><strong>{m.value}</strong><p>{m.detail}</p><small>{m.source} · {m.cadence}{m.observedAt?` · ${m.observedAt}`:""}</small>{m.change&&<b>{m.change}</b>}</a>)}{!metrics.length&&<Empty text="No supported official CMA series returned for this category."/>}</div></div>}
function CompareBoard({ids,setIds,data,events}:{ids:string[];setIds:(v:string[])=>void;data:Record<string,Payload>;events:LiveEvent[]}){const rows=ids.map(id=>{const c=metros.find(m=>m.id===id)!,d=data[id],m=d?.metrics??[],v=(x:string)=>m.find(q=>q.id===x),near=events.filter(e=>hav(c.lat,c.lng,e.lat,e.lng)<=c.radiusKm*1.8).length;return {c,pop:v("population")?.value??`${c.populationFallback.toFixed(2)}M`,un:v("unemployment")?.value??"—",starts:v("housing-starts")?.value??"—",permits:v("building-permits")?.value??"—",near}});return <div className="compare-board"><SectionIntro title="Compare metros" copy="Normalize interpretation mentally: raw counts naturally favour larger metros. Rates are directly comparable; counts are shown with geography labels."/><div className="compare-selects">{ids.map((id,i)=><select key={i} value={id} onChange={e=>{const n=[...ids];n[i]=e.target.value;setIds(n)}}>{metros.map(m=><option value={m.id} key={m.id}>{m.name}</option>)}</select>)}</div><div className="compare-table-wrap"><table><thead><tr><th>Indicator</th>{rows.map(r=><th key={r.c.id}>{r.c.name}</th>)}</tr></thead><tbody><tr><td>Population</td>{rows.map(r=><td key={r.c.id}>{r.pop}</td>)}</tr><tr><td>Unemployment</td>{rows.map(r=><td key={r.c.id}>{r.un}</td>)}</tr><tr><td>Housing starts</td>{rows.map(r=><td key={r.c.id}>{r.starts}</td>)}</tr><tr><td>Building permits</td>{rows.map(r=><td key={r.c.id}>{r.permits}</td>)}</tr><tr><td>Mapped local signals</td>{rows.map(r=><td key={r.c.id}>{r.near}</td>)}</tr></tbody></table></div></div>}
function SectionIntro({title,copy}:{title:string;copy:string}){return <div className="city-section-intro"><span>LOCAL ANALYSIS</span><h4>{title}</h4><p>{copy}</p></div>}
function Empty({text}:{text:string}){return <div className="city-empty">{text}</div>}
