"use client";

import dynamic from "next/dynamic";
import Link from "next/link";
import {useEffect,useMemo,useState} from "react";
import "./simulator.css";
import ProjectionsPanel from "./ProjectionsPanel";

const CanadaMap=dynamic(()=>import("./CanadaMap"),{ssr:false,loading:()=> <div className="sim-map-loading">Loading Canadian operating picture…</div>});

type Severity="critical"|"elevated"|"watch"|"stable";
type LiveEvent={id:string;title:string;summary:string;lat:number;lng:number;severity:Severity;source:string;sourceUrl:string;category:string;occurredAt:string;location?:string};
type Province={id:string;name:string;abbr:string;lat:number;lng:number;population:number;housing:number;grid:number;health:number;climate:number;transit:number;productivity:number};
type Scenario={homes:number;cleanPower:number;transit:number;health:number;adaptation:number;productivity:number};
type OpenMetric={id:string;label:string;value:string;raw?:number;unit?:string;detail:string;source:string;sourceUrl:string;observedAt?:string;status:"live"|"reference"|"unavailable"};
type OpenDataPayload={fetchedAt:string;metrics:OpenMetric[];availableFeeds:number;totalFeeds:number;sourceStatus:Record<string,boolean>};

const provinces:Province[]=[
{id:"BC",name:"British Columbia",abbr:"BC",lat:53.7,lng:-124.8,population:5.7,housing:61,grid:86,health:72,climate:63,transit:67,productivity:76},{id:"AB",name:"Alberta",abbr:"AB",lat:54.4,lng:-115.1,population:5.0,housing:72,grid:58,health:73,climate:55,transit:54,productivity:83},{id:"SK",name:"Saskatchewan",abbr:"SK",lat:54.4,lng:-106.4,population:1.25,housing:78,grid:55,health:70,climate:57,transit:43,productivity:75},{id:"MB",name:"Manitoba",abbr:"MB",lat:54.6,lng:-97.2,population:1.5,housing:76,grid:91,health:71,climate:60,transit:51,productivity:70},{id:"ON",name:"Ontario",abbr:"ON",lat:50.1,lng:-85.3,population:16.2,housing:55,grid:84,health:74,climate:67,transit:72,productivity:82},{id:"QC",name:"Quebec",abbr:"QC",lat:52.2,lng:-71.8,population:9.1,housing:69,grid:94,health:75,climate:70,transit:74,productivity:74},{id:"NB",name:"New Brunswick",abbr:"NB",lat:46.6,lng:-66.3,population:.86,housing:75,grid:69,health:68,climate:65,transit:42,productivity:65},{id:"NS",name:"Nova Scotia",abbr:"NS",lat:45.1,lng:-63.3,population:1.08,housing:64,grid:61,health:68,climate:64,transit:50,productivity:67},{id:"PE",name:"Prince Edward Island",abbr:"PE",lat:46.4,lng:-63.4,population:.18,housing:68,grid:72,health:66,climate:62,transit:38,productivity:63},{id:"NL",name:"Newfoundland and Labrador",abbr:"NL",lat:53.1,lng:-59.5,population:.55,housing:77,grid:82,health:67,climate:58,transit:40,productivity:69},{id:"YT",name:"Yukon",abbr:"YT",lat:64.0,lng:-135.0,population:.047,housing:60,grid:70,health:69,climate:50,transit:34,productivity:68},{id:"NT",name:"Northwest Territories",abbr:"NT",lat:64.8,lng:-124.8,population:.045,housing:52,grid:48,health:65,climate:45,transit:31,productivity:69},{id:"NU",name:"Nunavut",abbr:"NU",lat:70.3,lng:-86.0,population:.041,housing:39,grid:39,health:58,climate:41,transit:25,productivity:57}
];
const initialScenario:Scenario={homes:0,cleanPower:0,transit:0,health:0,adaptation:0,productivity:0};
const clamp=(n:number)=>Math.max(0,Math.min(100,n));
function scoreProvince(p:Province,s:Scenario){const housing=clamp(p.housing+s.homes*.55+s.transit*.08),grid=clamp(p.grid+s.cleanPower*.42+s.adaptation*.08),health=clamp(p.health+s.health*.46+s.homes*.04),climate=clamp(p.climate+s.adaptation*.5+s.cleanPower*.13),transit=clamp(p.transit+s.transit*.5+s.homes*.05),productivity=clamp(p.productivity+s.productivity*.38+s.transit*.08+s.cleanPower*.04);return {housing,grid,health,climate,transit,productivity,resilience:(housing+grid+health+climate+transit+productivity)/6};}

export default function SimulatorPage(){
 const [scenario,setScenario]=useState<Scenario>(initialScenario),[selected,setSelected]=useState("CA"),[events,setEvents]=useState<LiveEvent[]>([]),[status,setStatus]=useState<"loading"|"live"|"partial">("loading"),[layer,setLayer]=useState<"situation"|"resilience"|"housing"|"grid">("situation"),[horizon,setHorizon]=useState(2035),[openData,setOpenData]=useState<OpenDataPayload|null>(null);
 useEffect(()=>{let cancelled=false;Promise.allSettled([fetch("/api/intelligence",{cache:"no-store"}).then(r=>r.ok?r.json():Promise.reject()),fetch("/api/news",{cache:"no-store"}).then(r=>r.ok?r.json():Promise.reject())]).then(results=>{if(cancelled)return;const merged:LiveEvent[]=[];const intel=results[0].status==="fulfilled"?results[0].value:null,news=results[1].status==="fulfilled"?results[1].value:null;for(const e of intel?.events??[]){if(e.lat>=40&&e.lat<=84&&e.lng>=-142&&e.lng<=-50)merged.push({id:`intel-${e.id}`,title:e.title,summary:e.summary,lat:e.lat,lng:e.lng,severity:e.severity,source:e.source,sourceUrl:e.sourceUrl,category:e.layer??e.category??"Hazard",occurredAt:e.occurredAt,location:e.location});}for(const s of news?.stories??[]){if((s.region==="Canada"||/canada|canadian|ontario|quebec|alberta|british columbia|manitoba|saskatchewan|nova scotia|new brunswick|newfoundland|nunavut|yukon|northwest territories/i.test(`${s.title} ${s.summary}`))&&s.location)merged.push({id:`news-${s.id}`,title:s.title,summary:s.summary,lat:s.location.lat,lng:s.location.lng,severity:s.level,source:s.source,sourceUrl:s.articleUrl,category:s.category,occurredAt:s.publishedAt,location:s.location.name});}setEvents(merged.sort((a,b)=>Date.parse(b.occurredAt)-Date.parse(a.occurredAt)).slice(0,180));setStatus(results.every(r=>r.status==="fulfilled")?"live":"partial");});return()=>{cancelled=true};},[]);
 useEffect(()=>{let cancelled=false;fetch("/api/canada-open-data",{cache:"no-store"}).then(r=>r.ok?r.json():Promise.reject()).then(data=>{if(!cancelled)setOpenData(data as OpenDataPayload)}).catch(()=>{if(!cancelled)setOpenData({fetchedAt:new Date().toISOString(),metrics:[],availableFeeds:0,totalFeeds:4,sourceStatus:{}})});return()=>{cancelled=true};},[]);
 const selectedProvince=provinces.find(p=>p.id===selected);const aggregate=useMemo(()=>{const total=provinces.reduce((a,p)=>a+p.population,0),sums=provinces.reduce((acc,p)=>{const s=scoreProvince(p,scenario);for(const k of Object.keys(s) as Array<keyof typeof s>)acc[k]+=s[k]*p.population;return acc;},{housing:0,grid:0,health:0,climate:0,transit:0,productivity:0,resilience:0});for(const k of Object.keys(sums) as Array<keyof typeof sums>)sums[k]/=total;return sums;},[scenario]);const focus=selectedProvince?scoreProvince(selectedProvince,scenario):aggregate;
 const investment=Math.round((scenario.homes*1.8+scenario.cleanPower*1.35+scenario.transit*1.55+scenario.health*1.2+scenario.adaptation*.9+scenario.productivity*.75)*10)/10,horizonFactor=(horizon-2026)/9,homesAdded=Math.round(scenario.homes*17500*horizonFactor),cleanAdded=Math.round(scenario.cleanPower*410*horizonFactor)/10,transitGain=Math.round(scenario.transit*.12*horizonFactor*10)/10,highEvents=events.filter(e=>e.severity==="critical"||e.severity==="elevated").length,pressure=Math.min(100,Math.max(0,Math.round((100-focus.resilience)+(highEvents*1.8))));const change=(key:keyof Scenario,value:number)=>setScenario(s=>({...s,[key]:value}));
 return <main className="sim-root">
  <header className="sim-topbar"><Link href="/" className="sim-brand">ATLAS<span>.</span></Link><div><p>NATIONAL ANALYSIS WORKSPACE</p><h1>Canada Simulator</h1></div><nav><Link href="/">World</Link><Link href="/intelligence">Intelligence</Link><b>Simulator</b></nav><span className={`sim-live ${status}`}><i/>{status==="loading"?"SYNCING":status.toUpperCase()}</span></header>
  <section className="analyst-brief"><div><span className="eyebrow">CANADA / CURRENT OPERATING PICTURE</span><h2>National Situation & Scenario Analysis</h2><p>Read the current map first, select a geography, then apply policy assumptions to test directional effects. <b>Observed signals and reference infrastructure are separate from simulated outputs.</b></p></div><div className="brief-kpis"><Kpi label="National pressure" value={`${pressure}/100`} note="composite model"/><Kpi label="High-severity signals" value={String(highEvents)} note="live feed"/><Kpi label="Mapped live signals" value={String(events.length)} note="Canada-resolved"/><Kpi label="Projection horizon" value={String(horizon)} note="scenario"/></div></section>

  <div className="sim-workspace">
   <section className="sim-map-card"><div className="sim-section-head"><div><span>01 / OBSERVE</span><h3>National operating picture</h3><p>Live events overlaid on a persistent Canadian reference network.</p></div><div className="sim-tabs">{(["situation","resilience","housing","grid"] as const).map(x=><button key={x} className={layer===x?"active":""} onClick={()=>setLayer(x)}>{x==="situation"?"Current situation":x}</button>)}</div></div><CanadaMap provinces={provinces} events={events} scenario={scenario} selected={selected} onSelect={setSelected} layer={layer}/><div className="sim-map-footer"><span><i className="critical"/>Critical</span><span><i className="elevated"/>Elevated</span><span><i className="watch"/>Watch</span><span><i className="stable"/>Stable</span><strong>Reference markers are context, not incidents.</strong></div></section>
   <aside className="sim-controls"><div className="sim-section-head"><div><span>02 / ASSUME</span><h3>Scenario assumptions</h3><p>Set intervention intensity, then compare projected system scores.</p></div><button className="reset" onClick={()=>setScenario(initialScenario)}>Reset</button></div><label className="sim-horizon"><span>Projection horizon</span><b>{horizon}</b><input type="range" min="2030" max="2050" step="5" value={horizon} onChange={e=>setHorizon(Number(e.target.value))}/></label><Slider label="Housing delivery" help="Adds housing capacity; minor transit/health spillovers." value={scenario.homes} onChange={v=>change("homes",v)}/><Slider label="Power-system expansion" help="Adds clean generation and grid readiness." value={scenario.cleanPower} onChange={v=>change("cleanPower",v)}/><Slider label="Transit / mobility" help="Raises access and productivity connectivity." value={scenario.transit} onChange={v=>change("transit",v)}/><Slider label="Health-system capacity" help="Raises modelled service capacity." value={scenario.health} onChange={v=>change("health",v)}/><Slider label="Climate adaptation" help="Raises hazard resilience and grid hardening." value={scenario.adaptation} onChange={v=>change("adaptation",v)}/><Slider label="Productivity / innovation" help="Raises modelled economic capacity." value={scenario.productivity} onChange={v=>change("productivity",v)}/><div className="sim-cost"><span>SCENARIO ENVELOPE</span><strong>${investment}B</strong><small>Illustrative program scale — not a government cost estimate.</small></div></aside>
  </div>

  <section className="open-data-panel"><div className="sim-section-head"><div><span>03 / MEASURE</span><h3>Canadian open-data pulse</h3><p>Direct public feeds that refresh independently of the Atlas news layer. Values remain source-labelled and timestamped.</p></div><div className="data-health"><b>{openData?.availableFeeds??0}/{openData?.totalFeeds??4}</b><span>feeds responding</span></div></div><div className="open-metric-grid">{openData?.metrics.map(metric=><a key={metric.id} href={metric.sourceUrl} target="_blank" rel="noreferrer" className="open-metric"><div><span>{metric.label}</span><i>LIVE</i></div><strong>{metric.value}</strong><p>{metric.detail}</p><small>{metric.source}{metric.observedAt?` · ${metric.observedAt}`:""}</small></a>)}{!openData&&Array.from({length:8}).map((_,i)=><div key={i} className="open-metric loading"><span>SYNCING PUBLIC DATA</span><strong>—</strong><p>Connecting to Canadian open-data services…</p></div>)}{openData&&openData.metrics.length===0&&<div className="open-data-empty">Public-data feeds are temporarily unavailable. The simulator remains usable with Atlas live signals and reference data.</div>}</div><div className="coverage-strip"><span>CONNECTED NOW</span><b>Monetary policy</b><b>FX</b><b>Inflation</b><b>Bond yields</b><b>Weather alerts</b><b>Air quality</b><b>Water monitoring</b><b>Population projections</b></div></section>

  <section className="sim-output"><div className="sim-section-head"><div><span>04 / ASSESS</span><h3>{selectedProvince?selectedProvince.name:"Canada"} — projected effects</h3><p>Prototype normalized indices. Compare direction and relative magnitude, not point forecasts.</p></div><select value={selected} onChange={e=>setSelected(e.target.value)}><option value="CA">Canada</option>{provinces.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></div><div className="sim-score-grid"><Score label="Resilience" value={focus.resilience}/><Score label="Housing" value={focus.housing}/><Score label="Grid" value={focus.grid}/><Score label="Health" value={focus.health}/><Score label="Climate" value={focus.climate}/><Score label="Mobility" value={focus.transit}/><Score label="Productivity" value={focus.productivity}/></div><div className="sim-projections"><article><span>HOUSING CAPACITY</span><strong>+{homesAdded.toLocaleString()}</strong><small>scenario-equivalent homes by {horizon}</small></article><article><span>POWER CAPACITY</span><strong>+{cleanAdded} GW</strong><small>scenario-equivalent build-out</small></article><article><span>MOBILITY INDEX</span><strong>+{transitGain} pts</strong><small>modelled access improvement</small></article><article><span>COMPOSITE RESILIENCE</span><strong>{Math.round(focus.resilience)}</strong><small>normalized 0–100 prototype score</small></article></div></section>

  <ProjectionsPanel horizon={horizon} resilience={focus.resilience} scenarioIntensity={(scenario.homes+scenario.cleanPower+scenario.transit+scenario.health+scenario.adaptation+scenario.productivity)/6}/>

  <section className="sim-bottom-grid"><div className="sim-feed"><div className="sim-section-head"><div><span>05 / TRIAGE</span><h3>Canadian signal queue</h3><p>Recent Canada-resolved Atlas items for analyst review.</p></div><small>{events.length} mapped</small></div>{events.slice(0,10).map(e=><a key={e.id} href={e.sourceUrl} target="_blank" rel="noreferrer"><i className={e.severity}/><div><span>{e.category} · {e.location??e.source}</span><strong>{e.title}</strong><small>{e.source}</small></div><b>↗</b></a>)}{!events.length&&<p className="sim-empty">No Canadian Atlas signals are available from the current feeds.</p>}</div><div className="sim-method"><span>ANALYST NOTE</span><h3>Data confidence</h3><div className="confidence"><p><b>Observed</b><span>Live Atlas hazard/news feeds with Canadian coordinates.</span></p><p><b>Reference</b><span>Curated public locations for spatial context; not incident indicators.</span></p><p><b>Baseline</b><span>Prototype normalized provincial indicators; direct federal open-data feeds now appear separately above.</span></p><p><b>Simulated</b><span>Deterministic scenario weights. Directional exploration only.</span></p></div><p className="method-note">The analyst workflow intentionally keeps evidence and model output visually distinct so a projected effect cannot be mistaken for a current condition.</p><div><a href="https://www.statcan.gc.ca/en/developers/wds" target="_blank" rel="noreferrer">Statistics Canada WDS ↗</a><a href="https://api.weather.gc.ca/" target="_blank" rel="noreferrer">ECCC GeoMet ↗</a><a href="https://www.bankofcanada.ca/valet/" target="_blank" rel="noreferrer">Bank of Canada Valet ↗</a><a href="https://open.canada.ca/en/open-data" target="_blank" rel="noreferrer">Open Government Canada ↗</a></div></div></section>
 </main>;
}
function Slider({label,help,value,onChange}:{label:string;help:string;value:number;onChange:(v:number)=>void}){return <label className="sim-slider"><div><span>{label}<small>{help}</small></span><b>{value}%</b></div><input type="range" min="0" max="100" step="5" value={value} onChange={e=>onChange(Number(e.target.value))}/></label>}
function Score({label,value}:{label:string;value:number}){return <article className="sim-score"><div><span>{label}</span><b>{Math.round(value)}</b></div><meter min="0" max="100" value={value}/></article>}
function Kpi({label,value,note}:{label:string;value:string;note:string}){return <article><span>{label}</span><strong>{value}</strong><small>{note}</small></article>}
