export const runtime="edge";
import {metroById} from "../../simulator/city-data";

type Member={memberId:number;memberNameEn?:string;terminated?:number};
type Dimension={dimensionPositionId:number;dimensionNameEn?:string;member?:Member[]};
type Meta={releaseTime?:string;dimension?:Dimension[]};
type CityMetric={id:string;label:string;value:string;raw?:number;detail:string;source:string;sourceUrl:string;observedAt?:string;cadence:string;change?:string;group:"people"|"housing"|"economy"};
type Spec={id:string;label:string;productId:number;group:CityMetric["group"];detail:string;cadence:string;sourceUrl:string;selectors?:Array<{dimension:string[];members:string[]}>;format:(n:number)=>string};
const norm=(s:string)=>s.toLowerCase().replace(/[^a-z0-9]+/g," ").trim();
const safeNum=(v:unknown)=>{const n=typeof v==="string"?Number(v):v;return typeof n==="number"&&Number.isFinite(n)?n:null};
const safeText=(v:unknown)=>typeof v==="string"?v:"";
const compact=(n:number)=>new Intl.NumberFormat("en-CA",{notation:"compact",maximumFractionDigits:1}).format(n);
const money=(n:number)=>new Intl.NumberFormat("en-CA",{style:"currency",currency:"CAD",notation:"compact",maximumFractionDigits:1}).format(n);
const pct=(n:number)=>`${n.toFixed(1)}%`;
async function post(url:string,body:unknown){const r=await fetch(url,{method:"POST",headers:{Accept:"application/json","Content-Type":"application/json","User-Agent":"Atlas-City-Intelligence/1.0"},body:JSON.stringify(body),signal:AbortSignal.timeout(8500)});if(!r.ok)throw new Error(String(r.status));return r.json() as Promise<any>}
const multiplier=(code:unknown)=>{const n=safeNum(code);return n===null||n<0||n>12?1:10**n};
function dimMatch(dims:Dimension[],aliases:string[]){const targets=aliases.map(norm);return dims.find(d=>targets.some(t=>norm(d.dimensionNameEn??"")===t))??dims.find(d=>targets.some(t=>norm(d.dimensionNameEn??"").includes(t)))}
function memberMatch(dim:Dimension|undefined,aliases:string[]){if(!dim)return null;const members=(dim.member??[]).filter(m=>m.terminated!==1);const targets=aliases.map(norm);for(const t of targets){const exact=members.find(m=>norm(m.memberNameEn??"")===t);if(exact)return exact}for(const t of targets){const fuzzy=members.find(m=>norm(m.memberNameEn??"").includes(t));if(fuzzy)return fuzzy}return null}
function defaultMember(dim:Dimension){const name=norm(dim.dimensionNameEn??"");const tries:string[][]=[];if(name.includes("gender")||name.includes("sex"))tries.push(["Total - Gender","Both sexes","Total, gender"]);if(name.includes("age"))tries.push(["15 years and over","All ages","Total, all ages"]);if(name.includes("statistics"))tries.push(["Estimate"]);if(name.includes("type of unit"))tries.push(["Total units"]);for(const t of tries){const m=memberMatch(dim,t);if(m)return m}return (dim.member??[]).find(m=>m.terminated!==1)??null}
async function metric(spec:Spec,cma:string):Promise<CityMetric>{
 const metadata=await post("https://www150.statcan.gc.ca/t1/wds/rest/getCubeMetadata",[{productId:spec.productId}]);const wrap=Array.isArray(metadata)?metadata[0]:metadata;const meta=(wrap?.object??wrap) as Meta;const dims=Array.isArray(meta.dimension)?meta.dimension:[];if(!dims.length)throw new Error("metadata");const coordinate=Array(10).fill(0);
 for(const d of dims){const dn=norm(d.dimensionNameEn??"");let m:Member|null=null;if(dn.includes("geography")){const cityName=cma.split(",")[0].trim();m=memberMatch(d,[cma,cityName]);if(!m)throw new Error(`geo:${cma}`)}if(!m){const sel=spec.selectors?.find(s=>s.dimension.some(x=>dn.includes(norm(x))));if(sel)m=memberMatch(d,sel.members)}if(!m)m=defaultMember(d);if(m&&d.dimensionPositionId>=1&&d.dimensionPositionId<=10)coordinate[d.dimensionPositionId-1]=m.memberId}
 const data=await post("https://www150.statcan.gc.ca/t1/wds/rest/getDataFromCubePidCoordAndLatestNPeriods",[{productId:spec.productId,coordinate:coordinate.join("."),latestN:3}]);const row=Array.isArray(data)?data[0]:data;const obj=row?.object??row;const pts=obj?.vectorDataPoint??obj?.vectorDataPoints??[];if(!Array.isArray(pts)||!pts.length)throw new Error("points");const latest=pts[pts.length-1],prev=pts.length>1?pts[pts.length-2]:null;const r=safeNum(latest?.value);if(r===null)throw new Error("value");const value=r*multiplier(latest?.scalarFactorCode??latest?.scalorFactorCode);let change: string|undefined;const pr=safeNum(prev?.value);if(pr!==null&&pr!==0){const pv=pr*multiplier(prev?.scalarFactorCode??prev?.scalorFactorCode);const d=((value-pv)/Math.abs(pv))*100;if(Number.isFinite(d))change=`${d>=0?"+":""}${d.toFixed(1)}% vs prior`}
 return {id:spec.id,label:spec.label,value:spec.format(value),raw:value,detail:spec.detail,source:`Statistics Canada · ${String(spec.productId).replace(/^(\d{2})(\d{2})(\d{4})$/,"$1-$2-$3-01")}`,sourceUrl:spec.sourceUrl,observedAt:safeText(latest?.refPer)||safeText(meta.releaseTime),cadence:spec.cadence,change,group:spec.group};
}
const SPECS:Spec[]=[
 {id:"population",label:"Population",productId:17100148,group:"people",detail:"Annual CMA population estimate.",cadence:"Annual",sourceUrl:"https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1710014801",selectors:[{dimension:["gender"],members:["Total - gender"]},{dimension:["age group"],members:["All ages"]}],format:compact},
 {id:"employment",label:"Employment",productId:14100459,group:"economy",detail:"Three-month moving average, seasonally adjusted.",cadence:"Monthly",sourceUrl:"https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1410045901",selectors:[{dimension:["labour force characteristics"],members:["Employment"]}],format:compact},
 {id:"unemployment",label:"Unemployment rate",productId:14100459,group:"economy",detail:"CMA three-month moving average, seasonally adjusted.",cadence:"Monthly",sourceUrl:"https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1410045901",selectors:[{dimension:["labour force characteristics"],members:["Unemployment rate"]}],format:pct},
 {id:"participation",label:"Participation rate",productId:14100459,group:"economy",detail:"CMA labour-force participation rate.",cadence:"Monthly",sourceUrl:"https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1410045901",selectors:[{dimension:["labour force characteristics"],members:["Participation rate"]}],format:pct},
 {id:"housing-starts",label:"Housing starts",productId:34100156,group:"housing",detail:"CMHC seasonally adjusted annual rate, total units.",cadence:"Monthly",sourceUrl:"https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=3410015601",selectors:[{dimension:["type of unit"],members:["Total units"]}],format:compact},
 {id:"building-permits",label:"Building permits",productId:34100292,group:"housing",detail:"Latest building-permit construction value.",cadence:"Monthly",sourceUrl:"https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=3410029201",selectors:[{dimension:["type of structure"],members:["Total, type of structure","Total, all structures"]},{dimension:["type of work"],members:["Total, type of work","Total, all types of work"]}],format:money}
];
export async function GET(request:Request){const u=new URL(request.url),id=u.searchParams.get("city")||"toronto",city=metroById(id);if(!city)return Response.json({error:"Unknown city"},{status:404});const settled=await Promise.allSettled(SPECS.map(s=>metric(s,city.cma)));const metrics=settled.flatMap(r=>r.status==="fulfilled"?[r.value]:[]);return Response.json({city,fetchedAt:new Date().toISOString(),metrics,available:metrics.length,total:SPECS.length},{headers:{"Cache-Control":"public, max-age=120, s-maxage=900, stale-while-revalidate=3600"}})}
