export const NEWS_CATEGORIES = [
  "Security",
  "Border Security",
  "Conflict",
  "Defense",
  "Arms Control",
  "Nuclear Affairs",
  "Peacekeeping",
  "Civil Unrest",
  "Diplomacy",
  "International Organizations",
  "Regional Blocs",
  "Politics",
  "Elections",
  "Governance",
  "Law & Justice",
  "Human Rights",
  "Intelligence",
  "Cybersecurity",
  "Digital Governance",
  "Internet Freedom",
  "Data Privacy",
  "Terrorism",
  "Crime",
  "Organized Crime",
  "Corruption",
  "Economy",
  "Finance",
  "Monetary Policy",
  "Sovereign Debt",
  "Markets",
  "Competition Policy",
  "Industrial Policy",
  "Manufacturing",
  "Consumer Affairs",
  "Housing",
  "Trade",
  "Sanctions",
  "Supply Chains",
  "Ports & Logistics",
  "Energy",
  "Critical Minerals",
  "Mining",
  "Natural Resources",
  "Technology",
  "Artificial Intelligence",
  "Telecommunications",
  "Space",
  "Science",
  "Climate",
  "Environment",
  "Biodiversity",
  "Forestry",
  "Disasters",
  "Disaster Risk Reduction",
  "Public Health",
  "Food Security",
  "Agriculture",
  "Fisheries",
  "Water",
  "Migration",
  "Demographics",
  "Infrastructure",
  "Urbanization",
  "Maritime",
  "Ocean Affairs",
  "Transport",
  "Aviation",
  "Rail",
  "Development",
  "Humanitarian Aid",
  "Labor",
  "Social Protection",
  "Education",
  "Society & Culture",
  "Religious Affairs",
  "Indigenous Affairs",
  "Tourism",
  "Media & Information",
  "Arctic & Polar",
  "World Affairs",
] as const;

export type NewsCategory = (typeof NEWS_CATEGORIES)[number];

const CATEGORY_RULES: Array<[NewsCategory, RegExp]> = [
  ["Elections", /election|electoral|ballot|polling station|vote count|campaign trail|referendum|runoff/i],
  ["Peacekeeping", /peacekeep|blue helmets|un peace mission|observer mission|peace operation/i],
  ["Arms Control", /arms control|disarmament|nonproliferation|non-proliferation|weapons inspection|weapons ban|arms treaty/i],
  ["Nuclear Affairs", /nuclear weapon|nuclear program|nuclear programme|nuclear talks|atomic agency|\biaea\b|uranium enrichment|nuclear test/i],
  ["Border Security", /border security|border patrol|border guard|border wall|frontier security|customs enforcement/i],
  ["Civil Unrest", /civil unrest|mass protest|demonstration|street protest|general strike|riot police|state of emergency|popular uprising/i],
  ["International Organizations", /united nations|\bun\b security council|world bank|international monetary fund|\bimf\b|world health organization|\bwho\b|international court/i],
  ["Regional Blocs", /european union|african union|\basean\b|mercosur|arab league|gulf cooperation council|\bgcc\b|brics|g7\b|g20\b/i],
  ["Sanctions", /sanction|asset freeze|blacklist|export control|trade restriction|embargo/i],
  ["Human Rights", /human rights|civil liberties|political prisoner|war crimes|rights abuse|freedom of (speech|religion|assembly)|discrimination/i],
  ["Humanitarian Aid", /humanitarian|aid convoy|relief supplies|refugee camp|displaced people|famine relief|red cross|red crescent|unhcr/i],
  ["Cybersecurity", /cyber|ransomware|malware|data breach|hacker|phishing|digital espionage|critical systems attack/i],
  ["Digital Governance", /digital governance|digital regulation|online safety law|platform regulation|digital identity|e-government|algorithmic accountability/i],
  ["Internet Freedom", /internet freedom|internet shutdown|online censorship|website blocking|social media ban|digital rights|network restriction/i],
  ["Data Privacy", /data privacy|privacy law|personal data|data protection|privacy regulator|surveillance law|facial recognition/i],
  ["Artificial Intelligence", /artificial intelligence|\bai\b|machine learning|large language model|generative ai|deepfake|neural network/i],
  ["Telecommunications", /telecom|5g|6g|broadband|mobile network|internet outage|undersea cable|fiber optic|spectrum auction/i],
  ["Space", /spacecraft|space station|satellite launch|rocket launch|lunar|moon mission|mars mission|orbit|astronaut|cosmonaut/i],
  ["Critical Minerals", /critical mineral|rare earth|lithium|cobalt|nickel|copper mine|mineral supply|graphite|uranium mining/i],
  ["Mining", /mining|mine project|mineral extraction|gold mine|iron ore|bauxite|smelter|mine workers/i],
  ["Ports & Logistics", /port operations|port authority|container terminal|cargo terminal|logistics hub|customs clearance|port congestion|dockworkers/i],
  ["Supply Chains", /supply chain|logistics|freight|container rate|warehouse|factory disruption|manufacturing bottleneck|shipping delay/i],
  ["Aviation", /aviation|airline|airport|airspace|flight ban|air traffic|aircraft maker|plane crash/i],
  ["Rail", /railway|railroad|high-speed rail|freight train|rail network|train service|train crash/i],
  ["Ocean Affairs", /ocean governance|marine conservation|high seas|seabed|exclusive economic zone|\beez\b|ocean treaty|marine pollution/i],
  ["Maritime", /maritime|shipping lane|cargo ship|merchant vessel|port closure|strait|canal transit|naval blockade|piracy|sea route/i],
  ["Transport", /railway|railroad|airline|airport|aviation|highway|public transit|transport network|train crash|plane crash/i],
  ["Disasters", /earthquake|tsunami|volcanic|hurricane|typhoon|cyclone|wildfire|landslide|avalanche|natural disaster|emergency response/i],
  ["Disaster Risk Reduction", /disaster risk|disaster preparedness|early warning system|resilience plan|emergency drill|risk reduction|disaster prevention/i],
  ["Climate", /climate change|global warming|greenhouse gas|carbon emission|net zero|heatwave|extreme weather|cop\d+|decarbon/i],
  ["Biodiversity", /biodiversity|endangered species|habitat loss|species protection|nature reserve|wildlife corridor|ecosystem restoration/i],
  ["Forestry", /forestry|forest management|logging|timber|reforestation|forest loss|forest fire|wood products/i],
  ["Natural Resources", /natural resources|resource extraction|resource governance|resource nationalism|land use|resource concession/i],
  ["Environment", /environment|pollution|biodiversity|deforestation|conservation|ecosystem|wildlife|protected area|plastic waste/i],
  ["Public Health", /public health|disease outbreak|epidemic|pandemic|vaccine|hospital|health ministry|healthcare|virus|cholera|malaria/i],
  ["Food Security", /food security|famine|hunger|malnutrition|grain shortage|food prices|food supply|world food programme|\bwfp\b/i],
  ["Agriculture", /agriculture|farmer|farming|harvest|crop|livestock|fertilizer|pesticide|agricultural/i],
  ["Fisheries", /fisheries|fishing fleet|fish stocks|illegal fishing|aquaculture|seafood exports|fishing rights/i],
  ["Water", /water security|water shortage|drought|reservoir|river basin|dam project|groundwater|desalination|water supply/i],
  ["Migration", /migration|migrant|refugee|asylum|border crossing|deportation|displacement|immigration|emigration/i],
  ["Demographics", /demographic|population growth|population decline|birth rate|fertility rate|aging population|census/i],
  ["Infrastructure", /infrastructure|power grid|bridge|road project|construction project|public works|data center|industrial park/i],
  ["Urbanization", /urbanization|urbanisation|city planning|smart city|municipal development|urban growth|megacity|city infrastructure/i],
  ["Housing", /housing|home prices|rent control|housing shortage|affordable homes|mortgage market|residential construction/i],
  ["Labor", /labor union|labour union|workers strike|employment|unemployment|wages|job market|workforce|collective bargaining/i],
  ["Social Protection", /social protection|social security|welfare reform|pension reform|cash transfer|unemployment benefit|safety net/i],
  ["Education", /education|school|university|student protest|curriculum|teacher|literacy|academic freedom/i],
  ["Science", /scientist|research study|scientific|laboratory|research institute|breakthrough|genome|quantum/i],
  ["Terrorism", /terroris|extremis|militant group|insurgent|suicide bombing|jihadist/i],
  ["Organized Crime", /organized crime|organised crime|criminal syndicate|drug cartel|trafficking network|mafia|gang violence|transnational crime/i],
  ["Corruption", /corruption|bribery|graft|embezzlement|kickback|anti-corruption|illicit finance|kleptocracy/i],
  ["Crime", /organized crime|drug trafficking|smuggling|money laundering|cartel|criminal network|kidnapping|corruption probe/i],
  ["Intelligence", /intelligence service|spy agency|espionage|classified document|covert operation|surveillance operation|intelligence chief/i],
  ["Defense", /defen[cs]e|military spending|armed forces|troops|missile system|fighter jet|warship|navy|army|air force|weapons/i],
  ["Conflict", /war|armed conflict|ceasefire|airstrike|missile strike|invasion|frontline|peacekeeping|hostilities|clashes/i],
  ["Security", /security|attack|border tension|national security|emergency alert|threat level|police operation/i],
  ["Diplomacy", /diplomat|diplomatic|summit|bilateral|multilateral|peace talks|negotiat|treaty|state visit|foreign minister|ambassador/i],
  ["Governance", /governance|public administration|civil service|cabinet reshuffle|government reform|anti-corruption|state institution/i],
  ["Law & Justice", /supreme court|constitutional court|court ruling|prosecutor|indictment|legislation|legal challenge|justice ministry|rule of law/i],
  ["Politics", /president|prime minister|parliament|congress|senate|political party|opposition leader|coalition government|constitutional crisis/i],
  ["Energy", /oil|natural gas|energy|electricity|power plant|nuclear power|solar|wind farm|pipeline|opec|lng|renewable/i],
  ["Trade", /trade deal|tariff|export|import|customs|world trade organization|\bwto\b|trade surplus|trade deficit|commerce/i],
  ["Monetary Policy", /monetary policy|interest rate|rate cut|rate hike|central bank|money supply|quantitative easing|inflation target/i],
  ["Sovereign Debt", /sovereign debt|debt restructuring|debt default|government bond|debt ceiling|credit rating|debt relief|bond yield/i],
  ["Competition Policy", /competition policy|antitrust|anti-trust|market dominance|competition regulator|monopoly|merger review/i],
  ["Industrial Policy", /industrial policy|state subsidy|industrial strategy|reshoring|friend-shoring|local content rule|strategic industry/i],
  ["Manufacturing", /manufacturing|factory output|industrial production|assembly plant|automaker|steel production|production line/i],
  ["Consumer Affairs", /consumer rights|consumer confidence|consumer spending|product recall|price controls|cost of living|household spending/i],
  ["Finance", /central bank|interest rate|banking|bank loan|sovereign debt|bond yield|currency|foreign exchange|financial regulator/i],
  ["Markets", /stock market|equity market|commodity price|market rally|market selloff|investor|shares|index futures|market volatility/i],
  ["Economy", /econom|inflation|recession|gross domestic product|\bgdp\b|consumer prices|business activity|fiscal|monetary/i],
  ["Development", /economic development|development aid|poverty reduction|world bank|infrastructure financing|sustainable development|\bsdgs?\b/i],
  ["Technology", /technology|semiconductor|microchip|robotics|digital platform|software|startup|cloud computing|tech company/i],
  ["Media & Information", /journalist|news media|press freedom|misinformation|disinformation|propaganda|social media|broadcasting/i],
  ["Religious Affairs", /religious freedom|faith leader|religious minority|church|mosque|temple|sectarian tension|pilgrimage/i],
  ["Indigenous Affairs", /indigenous|first nations|native land|tribal government|aboriginal|ancestral territory|indigenous rights/i],
  ["Tourism", /tourism|tourist arrivals|travel industry|visitor visa|hotel sector|heritage tourism|cruise tourism/i],
  ["Society & Culture", /society|culture|religion|ethnic|language policy|civil society|public opinion|community leader|cultural heritage/i],
  ["Arctic & Polar", /arctic|antarctic|polar region|north pole|south pole|greenland ice|sea ice/i],
];

export const categoryFor = (value: string): NewsCategory =>
  CATEGORY_RULES.find(([, rule]) => rule.test(value))?.[0] ?? "World Affairs";

